# Generated by Django 4.2.7 on 2024-03-24 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0005_rename_category_quiz_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Comments',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
