# Generated by Django 4.2.7 on 2024-03-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0007_alter_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
    ]
